@startuml

participant rdk as "RDK"

box os
participant boot as "Boot\nService"
participant device as "Device\nService"
participant auth as "Auth\nService"
participant account as "Account\nService"
end box

participant core as "Core SDK"
participant manage as "Manage SDK"
participant ui as "UI"

participant distributor as "Distributor Service"
actor user as "User"

group OS Bootup
    boot -> device: check if device is provisioned
    device --> rdk : get device provision info
    rdk -> boot : provision details
    group Not Provisioned
        boot -> ui :launch
        ui -> core:Authentication.token("device")
        core --> auth:
        auth --> rdk: Get auth token
        rdk --> auth:
        auth --> core:
        core -> ui:Device Token
        ui -> core:Device.id()
        core --> device:
        device --> rdk: get mac address
        rdk --> device:
        device --> core:
        core -> ui:Mac Address
        ui -> distributor:Provision
        note right of ui: Distributor uses the sensitive device info \nto setup billing and services.
        distributor -> ui:Account Id, Device Id
        ui -> manage:Device.provision(accountId, deviceId)
        manage --> device:
        device --> rdk: set provision info
        rdk --> device:
        device --> manage:
        manage -> ui:status
        ui -> distributor:activate
        note right of ui: Lets the distributor know that\nthe device is fully activated
        distributor -> ui: status
        ui -> ui:Continue to \nSession update
    end
    group Provisioned
        boot -> account : get session
        account --> rdk: get session token info
        rdk -> boot : session details
        boot -> ui :launch
        group Session update
            ui -> core:Authentication.token("device")
            core --> auth:
            auth --> rdk: Get auth token
            rdk --> auth:
            auth --> core:
            core -> ui:Device Token
            ui -> distributor:Get platform Token
            ui -> manage:Account.session(token)
            manage --> account:
            account --> rdk: Push session token
            rdk --> account:
            account --> manage:
            manage -> ui:status
        end
    end

end


@enduml